"""Trusted, versioned pressure model artifact persistence."""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import joblib
from sklearn.pipeline import Pipeline

MODEL_FILE = "model.joblib"
METADATA_FILE = "metadata.json"
ARTIFACT_SCHEMA_VERSION = 1


class MissingPressureModelError(FileNotFoundError):
    """No trained pressure model has been deployed."""


@dataclass(frozen=True)
class PressureArtifact:
    model: Pipeline
    metadata: dict[str, Any]


def save_artifact(directory: Path, model: Pipeline, metadata: dict[str, Any]) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, directory / MODEL_FILE)
    (directory / METADATA_FILE).write_text(
        json.dumps(metadata, indent=2, sort_keys=True), encoding="utf-8"
    )


def load_artifact(directory: Path) -> PressureArtifact:
    model_path = directory / MODEL_FILE
    metadata_path = directory / METADATA_FILE
    if not model_path.is_file() or not metadata_path.is_file():
        raise MissingPressureModelError(
            "Regional pressure model artifact is unavailable"
        )
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    if metadata.get("schema_version") != ARTIFACT_SCHEMA_VERSION:
        raise ValueError("Unsupported pressure artifact schema version")
    if not metadata.get("model_version") or not metadata.get("feature_names"):
        raise ValueError("Incomplete pressure artifact metadata")
    # joblib uses pickle; only load artifacts generated by the trusted training CLI.
    model = joblib.load(model_path)
    if not isinstance(model, Pipeline):
        raise TypeError("Pressure artifact does not contain a model pipeline")
    return PressureArtifact(model=model, metadata=metadata)
