"""Trusted, versioned pressure model artifact persistence."""

import json
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

import joblib
from sklearn.pipeline import Pipeline

MODEL_FILE = "model.joblib"
METADATA_FILE = "metadata.json"
V2_MODEL_FILE = "visitor_pressure_model_v2.joblib"
V2_METADATA_FILE = "model_metadata_v2.json"
V2_EXPLANATION_METADATA_FILE = "explanation_metadata_v2.json"
ARTIFACT_SCHEMA_VERSION = 1


class MissingPressureModelError(FileNotFoundError):
    """No trained pressure model has been deployed."""


@dataclass(frozen=True)
class PressureArtifact:
    model: Pipeline
    metadata: dict[str, Any]
    feature_names: tuple[str, ...]
    target_type: str


def save_artifact(directory: Path, model: Pipeline, metadata: dict[str, Any]) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, directory / MODEL_FILE)
    (directory / METADATA_FILE).write_text(
        json.dumps(metadata, indent=2, sort_keys=True), encoding="utf-8"
    )


def artifact_paths(directory: Path) -> tuple[Path, Path, Path | None]:
    """Prefer the finalized v2 artifact while retaining legacy test support."""
    if (directory / V2_MODEL_FILE).is_file() or (
        directory / V2_METADATA_FILE
    ).is_file():
        return (
            directory / V2_MODEL_FILE,
            directory / V2_METADATA_FILE,
            directory / V2_EXPLANATION_METADATA_FILE,
        )
    return directory / MODEL_FILE, directory / METADATA_FILE, None


@lru_cache(maxsize=8)
def _load_artifact_cached(
    model_path: Path,
    metadata_path: Path,
    explanation_path: Path | None,
    stamps: tuple[tuple[int, int], ...],
) -> PressureArtifact:
    del stamps  # The file stamps are intentionally part of the cache key.
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    loaded = joblib.load(model_path)
    if explanation_path is not None:
        if metadata.get("schema_version") != 2:
            raise ValueError("Unsupported selected pressure artifact schema version")
        if not isinstance(loaded, dict) or not isinstance(
            loaded.get("model"), Pipeline
        ):
            raise TypeError("Selected pressure artifact has an invalid payload")
        model = loaded["model"]
        feature_names = tuple(loaded.get("feature_names", ()))
        if loaded.get("target_type") != "residual":
            raise ValueError("Selected pressure model must predict residual occupancy")
        if feature_names != tuple(metadata.get("feature_names", ())):
            raise ValueError("Selected model and metadata feature order differ")
        if explanation_path.is_file():
            explanation_metadata = json.loads(
                explanation_path.read_text(encoding="utf-8")
            )
            if explanation_metadata.get("model_version") != metadata.get(
                "model_version"
            ):
                raise ValueError("Explanation metadata model version differs")
            metadata = {**metadata, **explanation_metadata}
        target_type = "residual"
    else:
        if metadata.get("schema_version") != ARTIFACT_SCHEMA_VERSION:
            raise ValueError("Unsupported pressure artifact schema version")
        if not isinstance(loaded, Pipeline):
            raise TypeError("Pressure artifact does not contain a model pipeline")
        model = loaded
        feature_names = tuple(metadata.get("feature_names", ()))
        target_type = "direct_occupancy"
    if not metadata.get("model_version") or not feature_names:
        raise ValueError("Incomplete pressure artifact metadata")
    return PressureArtifact(
        model=model,
        metadata=metadata,
        feature_names=feature_names,
        target_type=target_type,
    )


def load_artifact(directory: Path) -> PressureArtifact:
    model_path, metadata_path, explanation_path = artifact_paths(directory)
    if not model_path.is_file() or not metadata_path.is_file():
        raise MissingPressureModelError(
            "Regional pressure model artifact is unavailable"
        )
    paths = [model_path, metadata_path]
    if explanation_path is not None and explanation_path.is_file():
        paths.append(explanation_path)
    stamps = tuple((path.stat().st_mtime_ns, path.stat().st_size) for path in paths)
    # joblib uses pickle; only load artifacts generated by the trusted training CLI.
    return _load_artifact_cached(
        directory.resolve() / model_path.name,
        directory.resolve() / metadata_path.name,
        directory.resolve() / explanation_path.name
        if explanation_path and explanation_path.is_file()
        else None,
        stamps,
    )
